trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'

- script: |
    pip install -r requirements.txt
    python manage.py migrate
    python manage.py collectstatic --noinput
  displayName: 'Install dependencies and set up Django'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'AzureConnection'
    appName: 'django-todo-app'
    package: '.'
